# Generated by Django 5.0.14 on 2025-12-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="likes",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of likes for this teacher",
                verbose_name="Likes",
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="views",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of profile views", verbose_name="Views"
            ),
        ),
    ]
