# Generated by Django 5.0.14 on 2025-12-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_teacherprofile_likes_teacherprofile_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Video showing how the teacher teaches (3-5 minutes)",
                null=True,
                upload_to="teacher_videos/",
                verbose_name="Teaching Video",
            ),
        ),
    ]
