# Generated by Django 5.0.14 on 2025-12-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_teacherprofile_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="bio_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Biography (English)"
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="bio_ru",
            field=models.TextField(
                blank=True, null=True, verbose_name="Biography (Russian)"
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="bio_tm",
            field=models.TextField(
                blank=True, null=True, verbose_name="Biography (Turkmen)"
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="specialization_en",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Specialization (English)",
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="specialization_ru",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Specialization (Russian)",
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="specialization_tm",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Specialization (Turkmen)",
            ),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="Deprecated: Use bio_tm/ru/en instead",
                null=True,
                verbose_name="Biography (Legacy)",
            ),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="specialization",
            field=models.CharField(
                blank=True,
                help_text="Deprecated: Use specialization_tm/ru/en instead",
                max_length=255,
                null=True,
                verbose_name="Specialization (Legacy)",
            ),
        ),
    ]
