# Generated by Django 5.0.14 on 2025-12-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_studentprofile_parent_fields_and_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="parent_name",
            field=models.CharField(
                blank=True,
                help_text="Deprecated: Use parent1_name instead",
                max_length=255,
                null=True,
                verbose_name="Parent Name (Legacy)",
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="parent_phone",
            field=models.CharField(
                blank=True,
                help_text="Deprecated: Use parent1_phone instead",
                max_length=20,
                null=True,
                verbose_name="Parent Phone (Legacy)",
            ),
        ),
    ]
