# Generated by Django 5.0.14 on 2025-12-17 04:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_studentprofile_parent_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who liked this teacher profile",
                related_name="liked_teachers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Liked By",
            ),
        ),
    ]
