# Generated by Django 5.0.14 on 2025-12-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_add_head_teacher_and_merchant_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="rfid_uid",
            field=models.CharField(
                blank=True,
                help_text="Unique identifier from RFID bracelet",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="RFID UID",
            ),
        ),
    ]
