# Generated by Django 5.0.14 on 2026-01-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_studentprofile_rfid_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("boy", "Boy"), ("girl", "Girl")],
                max_length=10,
                null=True,
                verbose_name="Gender",
            ),
        ),
    ]
