# Generated by Django 5.0.14 on 2025-12-05 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subscriptions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionplan",
            index=models.Index(
                fields=["is_active"], name="subscriptio_is_acti_dd0689_idx"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="subscriptions.subscriptionplan",
                verbose_name="Plan",
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["user"], name="subscriptio_user_id_586440_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["status"], name="subscriptio_status_5e8870_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["end_date"], name="subscriptio_end_dat_60694b_idx"
            ),
        ),
    ]
