# Generated by Django 5.0.14 on 2025-12-05 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Student",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="courses.course",
                verbose_name="Course",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "student"},
                related_name="student_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Students",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "teacher"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teaching_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Teacher",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="courses.group",
                verbose_name="Group",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="courses.lesson",
                verbose_name="Lesson",
            ),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(
                fields=["course"], name="courses_gro_course__39816b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(
                fields=["teacher"], name="courses_gro_teacher_a4fea8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(
                fields=["is_active"], name="courses_gro_is_acti_85180e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(fields=["group"], name="courses_les_group_i_68cb63_idx"),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["lesson_date"], name="courses_les_lesson__7a811c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["student"], name="courses_gra_student_8373a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["lesson"], name="courses_gra_lesson__566399_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="grade",
            unique_together={("student", "lesson")},
        ),
    ]
