# Generated by Django 5.0.14 on 2025-12-24 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="time_slot",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "08:00 - 11:00"),
                    ("B", "13:00 - 17:00"),
                    ("C", "17:00 - 19:00"),
                ],
                help_text="A: 08:00-11:00, B: 13:00-17:00, C: 17:00-19:00",
                max_length=1,
                null=True,
                verbose_name="Time Slot",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="week_days",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Monday, Wednesday, Friday"),
                    ("2", "Tuesday, Thursday, Saturday"),
                ],
                help_text="1: Monday/Wednesday/Friday, 2: Tuesday/Thursday/Saturday",
                max_length=1,
                null=True,
                verbose_name="Week Days",
            ),
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when the student started this course/group",
                        null=True,
                        verbose_name="Start Date",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when the student finished this course/group",
                        null=True,
                        verbose_name="End Date",
                    ),
                ),
                (
                    "final_grade",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional final grade for the whole course",
                        max_digits=5,
                        null=True,
                        verbose_name="Final Grade",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="courses.group",
                        verbose_name="Group",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enrollment",
                "verbose_name_plural": "Enrollments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["student"], name="courses_enr_student_5c0023_idx"
                    ),
                    models.Index(
                        fields=["group"], name="courses_enr_group_i_74bac2_idx"
                    ),
                    models.Index(
                        fields=["status"], name="courses_enr_status_4fd017_idx"
                    ),
                ],
                "unique_together": {("student", "group")},
            },
        ),
    ]
