# Generated by Django 5.0.14 on 2025-12-25 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_group_time_slot_group_week_days_enrollment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teaching_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Teacher",
            ),
        ),
    ]
