# Generated by Django 5.0.14 on 2025-12-26 17:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_group_teacher"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam_number",
                    models.PositiveIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4")],
                        help_text="Exam number (1-4)",
                        verbose_name="Exam Number",
                    ),
                ),
                (
                    "writing",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Writing component grade (0-100)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Writing",
                    ),
                ),
                (
                    "listening",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Listening component grade (0-100)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Listening",
                    ),
                ),
                (
                    "reading",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Reading component grade (0-100)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Reading",
                    ),
                ),
                (
                    "speaking",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Speaking component grade (0-100)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Speaking",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_grades",
                        to="courses.group",
                        verbose_name="Group",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_grades",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Grade",
                "verbose_name_plural": "Exam Grades",
                "ordering": ["group", "student", "exam_number"],
                "indexes": [
                    models.Index(
                        fields=["student", "group"],
                        name="courses_exa_student_30a8ca_idx",
                    ),
                    models.Index(
                        fields=["group", "exam_number"],
                        name="courses_exa_group_i_a53279_idx",
                    ),
                ],
                "unique_together": {("student", "group", "exam_number")},
            },
        ),
    ]
