# Generated by Django 5.0.14 on 2026-01-03 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_attendance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Game Title")),
                (
                    "game_type",
                    models.CharField(
                        choices=[("matching", "Matching (Drag & Drop)")],
                        default="matching",
                        max_length=50,
                        verbose_name="Game Type",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        default=list,
                        help_text="JSON data containing words and translations: [{'word': 'apple', 'translation': 'alma'}, ...]",
                        verbose_name="Game Data",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games",
                        to="courses.group",
                        verbose_name="Group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Game",
                "verbose_name_plural": "Games",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["group"], name="courses_gam_group_i_62bd21_idx"
                    )
                ],
            },
        ),
    ]
