# Generated by Django 5.0.14 on 2026-01-04 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_game"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AddField(
            model_name="game",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games",
                to="courses.lesson",
                verbose_name="Lesson",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="played_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="played_games",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Played By Students",
            ),
        ),
    ]
