# Generated by Django 5.0.14 on 2026-01-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0009_gameattempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="game_type",
            field=models.CharField(
                choices=[
                    ("matching", "Matching (Drag & Drop)"),
                    ("sprint", "True or False Sprint"),
                ],
                default="matching",
                max_length=50,
                verbose_name="Game Type",
            ),
        ),
    ]
