# Generated by Django 5.0.14 on 2026-01-06 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_alter_game_game_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Scheme Name")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Exam Scheme",
                "verbose_name_plural": "Exam Schemes",
            },
        ),
        migrations.CreateModel(
            name="ExamType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "writing_weight",
                    models.PositiveIntegerField(
                        default=25, verbose_name="Writing Weight"
                    ),
                ),
                (
                    "listening_weight",
                    models.PositiveIntegerField(
                        default=25, verbose_name="Listening Weight"
                    ),
                ),
                (
                    "reading_weight",
                    models.PositiveIntegerField(
                        default=25, verbose_name="Reading Weight"
                    ),
                ),
                (
                    "speaking_weight",
                    models.PositiveIntegerField(
                        default=25, verbose_name="Speaking Weight"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Exam Type",
                "verbose_name_plural": "Exam Types",
            },
        ),
        migrations.AddField(
            model_name="group",
            name="exam_scheme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="groups",
                to="courses.examscheme",
                verbose_name="Exam Scheme",
            ),
        ),
        migrations.CreateModel(
            name="ExamSchemeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight_percentage",
                    models.PositiveIntegerField(
                        help_text="How much this exam contributes to the final grade (0-100)",
                        verbose_name="Weight (%)",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1, verbose_name="Order")),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="courses.examscheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Scheme Item",
                "verbose_name_plural": "Exam Scheme Items",
                "ordering": ["order"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="examgrade",
            unique_together={("student", "group", "exam_number")},
        ),
        migrations.AddField(
            model_name="examgrade",
            name="exam_scheme_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grades",
                to="courses.examschemeitem",
                verbose_name="Exam Scheme Item",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examgrade",
            unique_together={
                ("student", "group", "exam_number"),
                ("student", "group", "exam_scheme_item"),
            },
        ),
        migrations.AddIndex(
            model_name="examgrade",
            index=models.Index(
                fields=["exam_scheme_item"], name="courses_exa_exam_sc_1ac70b_idx"
            ),
        ),
        migrations.AddField(
            model_name="examschemeitem",
            name="exam_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.examtype"
            ),
        ),
    ]
