# Generated by Django 5.0.14 on 2025-12-28 08:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_tm",
                    models.CharField(max_length=255, verbose_name="Name (Turkmen)"),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=255, verbose_name="Name (Russian)"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=255, verbose_name="Name (English)"),
                ),
                (
                    "description_tm",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description (Turkmen)"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description (Russian)"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description (English)"
                    ),
                ),
                (
                    "terminal_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique ID for the ESP32 terminal",
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Terminal ID",
                    ),
                ),
                (
                    "auth_token",
                    models.CharField(
                        blank=True,
                        default=uuid.uuid4,
                        help_text="Secret token for terminal authentication",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Terminal Auth Token",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor Profile",
                "verbose_name_plural": "Vendor Profiles",
            },
        ),
    ]
