# Generated by Django 5.0.14 on 2026-01-04 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0011_alter_game_game_type"),
        ("payments", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("bank_transfer", "Bank Transfer"),
                    ("card", "Card"),
                ],
                default="cash",
                max_length=20,
                verbose_name="Payment Method",
            ),
        ),
        migrations.RemoveField(
            model_name="paymentwebhook",
            name="payment_method",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="payments_pa_user_id_be07d0_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="payments_pa_transac_8e9d99_idx",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="completed_at",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="course",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="description",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="gateway_response",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="transaction_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="user",
        ),
        migrations.AddField(
            model_name="payment",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Comment"),
        ),
        migrations.AddField(
            model_name="payment",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: group this payment is for",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="courses.group",
                verbose_name="Group",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="invoice_number",
            field=models.CharField(
                blank=True,
                help_text="Unique identifier for this payment transaction",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Invoice Number",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="received_by",
            field=models.ForeignKey(
                help_text="Staff member (Head Teacher) who received the payment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Received By",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Student",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                ],
                default="completed",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["student"], name="payments_pa_student_2c03b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["invoice_number"], name="payments_pa_invoice_601934_idx"
            ),
        ),
        migrations.DeleteModel(
            name="PaymentMethod",
        ),
        migrations.DeleteModel(
            name="PaymentWebhook",
        ),
    ]
