# Generated by Django 5.0.14 on 2026-01-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0004_alter_payment_payment_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Discount amount applied to this payment",
                max_digits=10,
                verbose_name="Discount",
            ),
        ),
    ]
