# Generated by Django 5.0.14 on 2025-12-05 14:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("video", "Video"),
                            ("image", "Image"),
                            ("link", "Link"),
                            ("other", "Other"),
                        ],
                        default="document",
                        max_length=20,
                        verbose_name="Material Type",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="materials/",
                        verbose_name="File",
                    ),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="URL")),
                (
                    "is_premium",
                    models.BooleanField(default=False, verbose_name="Premium Content"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Material",
                "verbose_name_plural": "Materials",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "author",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Author"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="books/covers/",
                        verbose_name="Cover Image",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        upload_to="books/pdfs/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                        verbose_name="PDF File",
                    ),
                ),
                ("language", models.CharField(max_length=100, verbose_name="Language")),
                (
                    "level",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Level"
                    ),
                ),
                (
                    "is_premium",
                    models.BooleanField(
                        default=True,
                        help_text="Requires subscription to access",
                        verbose_name="Premium Content",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["language"], name="content_boo_languag_6ad9cf_idx"
                    ),
                    models.Index(
                        fields=["is_premium"], name="content_boo_is_prem_c16f10_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="content_boo_is_acti_858b67_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Audio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "audio_file",
                    models.FileField(
                        upload_to="audio/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["mp3", "wav", "ogg", "m4a"]
                            )
                        ],
                        verbose_name="Audio File",
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Duration (Seconds)"
                    ),
                ),
                ("language", models.CharField(max_length=100, verbose_name="Language")),
                (
                    "is_premium",
                    models.BooleanField(
                        default=True,
                        help_text="Requires subscription to access",
                        verbose_name="Premium Content",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audio_files",
                        to="content.book",
                        verbose_name="Related Book",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audio",
                "verbose_name_plural": "Audio Files",
                "ordering": ["-created_at"],
            },
        ),
    ]
