# Generated by Django 5.0.14 on 2025-12-05 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_initial"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="materials",
                to="courses.course",
                verbose_name="Course",
            ),
        ),
        migrations.AddIndex(
            model_name="audio",
            index=models.Index(fields=["book"], name="content_aud_book_id_ddd947_idx"),
        ),
        migrations.AddIndex(
            model_name="audio",
            index=models.Index(
                fields=["is_premium"], name="content_aud_is_prem_9f2795_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audio",
            index=models.Index(
                fields=["is_active"], name="content_aud_is_acti_77bb5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["material_type"], name="content_mat_materia_fc1103_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["course"], name="content_mat_course__e28373_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["is_premium"], name="content_mat_is_prem_d125a5_idx"
            ),
        ),
    ]
