# Generated by Django 5.0.14 on 2025-12-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Message Content")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="chat/files/",
                        verbose_name="File Attachment",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="File Name"
                    ),
                ),
                (
                    "is_edited",
                    models.BooleanField(default=False, verbose_name="Edited"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deleted"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageReadStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Read At"),
                ),
            ],
            options={
                "verbose_name": "Message Read Status",
                "verbose_name_plural": "Message Read Statuses",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Room Name")),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("course", "Course Chat"),
                            ("group", "Group Chat"),
                            ("direct", "Direct Message"),
                            ("general", "General Chat"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="Room Type",
                    ),
                ),
                (
                    "is_private",
                    models.BooleanField(default=False, verbose_name="Private Room"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Chat Room",
                "verbose_name_plural": "Chat Rooms",
                "ordering": ["-updated_at"],
            },
        ),
    ]
