# Generated by Django 5.0.14 on 2025-12-05 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0001_initial"),
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="messagereadstatus",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="read_statuses",
                to="chat.message",
                verbose_name="Message",
            ),
        ),
        migrations.AddField(
            model_name="messagereadstatus",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="read_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_rooms",
                to="courses.course",
                verbose_name="Course",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_rooms",
                to="courses.group",
                verbose_name="Group",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="chat_rooms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Participants",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.room",
                verbose_name="Room",
            ),
        ),
        migrations.AddIndex(
            model_name="messagereadstatus",
            index=models.Index(
                fields=["message"], name="chat_messag_message_91f5bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagereadstatus",
            index=models.Index(fields=["user"], name="chat_messag_user_id_376cf7_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="messagereadstatus",
            unique_together={("message", "user")},
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["room_type"], name="chat_room_room_ty_553388_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["course"], name="chat_room_course__201b64_idx"),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["group"], name="chat_room_group_i_ead7a2_idx"),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["is_active"], name="chat_room_is_acti_62adad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["room"], name="chat_messag_room_id_cee780_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["user"], name="chat_messag_user_id_5a3720_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["created_at"], name="chat_messag_created_b6b51c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["is_deleted"], name="chat_messag_is_dele_543a03_idx"
            ),
        ),
    ]
