# Generated by Django 5.0.14 on 2026-01-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("course", "Course Chat"),
                    ("group", "Group Chat"),
                    ("direct", "Direct Message"),
                    ("general", "General Chat"),
                    ("ai", "AI Assistant Chat"),
                ],
                default="general",
                max_length=20,
                verbose_name="Room Type",
            ),
        ),
    ]
