# Generated by Django 5.0.14 on 2025-12-27 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("view", "Просмотр"),
                            ("create", "Создание"),
                            ("update", "Обновление"),
                            ("delete", "Удаление"),
                            ("login", "Вход"),
                            ("logout", "Выход"),
                            ("export", "Экспорт"),
                            ("import", "Импорт"),
                            ("other", "Другое"),
                        ],
                        default="view",
                        max_length=20,
                        verbose_name="Тип действия",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время действия"
                    ),
                ),
                (
                    "page_path",
                    models.CharField(
                        help_text="Например: /cabinet/grades или /management/news",
                        max_length=500,
                        verbose_name="Путь страницы",
                    ),
                ),
                (
                    "component_name",
                    models.CharField(
                        blank=True,
                        help_text="Например: GradesPage.vue или NewsListPage.vue",
                        max_length=200,
                        null=True,
                        verbose_name="Название компонента",
                    ),
                ),
                (
                    "action_description",
                    models.TextField(
                        blank=True,
                        help_text='Например: "Редактировал студента Amanow Bahtyyar" или "Создал группу English basic winter 124"',
                        null=True,
                        verbose_name="Описание действия",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP адрес"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "object_type",
                    models.CharField(
                        blank=True,
                        help_text="Например: Student, Group, Course",
                        max_length=100,
                        null=True,
                        verbose_name="Тип объекта",
                    ),
                ),
                (
                    "object_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID объекта"
                    ),
                ),
                (
                    "object_name",
                    models.CharField(
                        blank=True,
                        help_text='Например: "Amanow Bahtyyar" или "English basic winter 124"',
                        max_length=200,
                        null=True,
                        verbose_name="Название объекта",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Дополнительные данные"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог активности",
                "verbose_name_plural": "Логи активности",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="activity_lo_timesta_28bc36_idx"
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="activity_lo_user_id_08a8e8_idx",
                    ),
                    models.Index(
                        fields=["action_type", "-timestamp"],
                        name="activity_lo_action__efdc42_idx",
                    ),
                    models.Index(
                        fields=["page_path", "-timestamp"],
                        name="activity_lo_page_pa_7f4758_idx",
                    ),
                ],
            },
        ),
    ]
