# Generated by Django 5.0.14 on 2025-12-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Image will be automatically compressed to ~100KB",
                        upload_to="news/images/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "title_tm",
                    models.CharField(max_length=255, verbose_name="Title (Turkmen)"),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=255, verbose_name="Title (Russian)"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=255, verbose_name="Title (English)"),
                ),
                ("content_tm", models.TextField(verbose_name="Content (Turkmen)")),
                ("content_ru", models.TextField(verbose_name="Content (Russian)")),
                ("content_en", models.TextField(verbose_name="Content (English)")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Published"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Featured news will be shown first",
                        verbose_name="Featured",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "News",
                "verbose_name_plural": "News",
                "ordering": ["-is_featured", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_published"], name="landing_new_is_publ_4f1e9a_idx"
                    ),
                    models.Index(
                        fields=["is_featured"], name="landing_new_is_feat_67e86d_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="landing_new_created_d77e7b_idx"
                    ),
                ],
            },
        ),
    ]
