# Generated by Django 5.0.14 on 2025-12-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="views",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of times this news has been viewed",
                verbose_name="Views",
            ),
        ),
    ]
