# Generated by Django 5.0.14 on 2025-12-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0003_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="likes",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of likes for this message",
                verbose_name="Likes",
            ),
        ),
    ]
