# Generated by Django 5.0.14 on 2025-12-07 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0004_contactmessage_likes"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="📚",
                        help_text="Emoji or icon for the category",
                        max_length=10,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "name_tm",
                    models.CharField(max_length=255, verbose_name="Name (Turkmen)"),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=255, verbose_name="Name (Russian)"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=255, verbose_name="Name (English)"),
                ),
                (
                    "description_tm",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description (Turkmen)"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description (Russian)"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description (English)"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order (lower number = higher priority)",
                        verbose_name="Order",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Course Category",
                "verbose_name_plural": "Course Categories",
                "ordering": ["order", "name_en"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "order"],
                        name="landing_cou_is_acti_0aefd3_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CourseSubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_tm",
                    models.CharField(max_length=255, verbose_name="Name (Turkmen)"),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=255, verbose_name="Name (Russian)"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=255, verbose_name="Name (English)"),
                ),
                (
                    "description_tm",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description (Turkmen)"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description (Russian)"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description (English)"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order within category",
                        verbose_name="Order",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="landing.coursecategory",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course SubCategory",
                "verbose_name_plural": "Course SubCategories",
                "ordering": ["category", "order", "name_en"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_tm",
                    models.CharField(max_length=255, verbose_name="Title (Turkmen)"),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=255, verbose_name="Title (Russian)"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=255, verbose_name="Title (English)"),
                ),
                (
                    "description_tm",
                    models.TextField(verbose_name="Description (Turkmen)"),
                ),
                (
                    "description_ru",
                    models.TextField(verbose_name="Description (Russian)"),
                ),
                (
                    "description_en",
                    models.TextField(verbose_name="Description (English)"),
                ),
                (
                    "duration_weeks",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Course duration in weeks",
                        verbose_name="Duration (Weeks)",
                    ),
                ),
                (
                    "hours_per_week",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Hours per Week"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Course price in TMT",
                        max_digits=10,
                        verbose_name="Price",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="landing.coursesubcategory",
                        verbose_name="SubCategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "ordering": ["subcategory", "title_en"],
            },
        ),
        migrations.AddIndex(
            model_name="coursesubcategory",
            index=models.Index(
                fields=["category", "is_active", "order"],
                name="landing_cou_categor_0e3231_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["subcategory", "is_active"],
                name="landing_cou_subcate_7b0bfa_idx",
            ),
        ),
    ]
