# Generated by Django 5.0.14 on 2025-12-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0005_coursecategory_coursesubcategory_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="discount_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Discounted price in TMT (will be shown crossed out)",
                max_digits=10,
                null=True,
                verbose_name="Discount Price",
            ),
        ),
    ]
