# Generated by Django 5.0.14 on 2025-12-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0006_course_discount_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Course image (will be automatically compressed to ~100KB)",
                null=True,
                upload_to="courses/images/",
                verbose_name="Image",
            ),
        ),
        migrations.AddField(
            model_name="coursecategory",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Category image (will be automatically compressed to ~100KB)",
                null=True,
                upload_to="course-categories/images/",
                verbose_name="Image",
            ),
        ),
        migrations.AddField(
            model_name="coursesubcategory",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Subcategory image (will be automatically compressed to ~100KB)",
                null=True,
                upload_to="course-subcategories/images/",
                verbose_name="Image",
            ),
        ),
    ]
