# Generated by Django 5.0.14 on 2025-12-17 04:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0007_course_image_coursecategory_image_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who liked this message",
                related_name="liked_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Liked By",
            ),
        ),
    ]
