# Generated by Django 5.0.14 on 2026-01-08 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "courses",
            "0012_examscheme_examtype_group_exam_scheme_examschemeitem_and_more",
        ),
        ("landing", "0008_contactmessage_liked_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="discount_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Discounted price in Gems (will be shown crossed out)",
                max_digits=10,
                null=True,
                verbose_name="Discount Price",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Course price in Gems",
                max_digits=10,
                verbose_name="Price",
            ),
        ),
        migrations.CreateModel(
            name="LeaderboardCarousel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_tm",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Title (Turkmen)"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Title (Russian)"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Title (English)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_slots",
                        to="courses.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "exam_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_slots",
                        to="courses.examtype",
                        verbose_name="Exam Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leaderboard Carousel",
                "verbose_name_plural": "Leaderboard Carousels",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
