# Generated by Django 5.0.14 on 2025-12-25 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0004_alter_group_teacher"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the message",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Message content", verbose_name="Content"
                    ),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("all", "All Users"),
                            ("students", "All Students"),
                            ("teachers", "All Teachers"),
                            ("directors", "All Directors"),
                            ("head_teachers", "All Head Teachers"),
                            ("groups", "Specific Groups"),
                            ("group_teachers", "Teachers of Specific Groups"),
                            ("custom", "Custom Selection"),
                        ],
                        help_text="Type of recipients for this message",
                        max_length=20,
                        verbose_name="Recipient Type",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Schedule message for later (optional)",
                        null=True,
                        verbose_name="Scheduled At",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the message was actually sent",
                        null=True,
                        verbose_name="Sent At",
                    ),
                ),
                (
                    "is_sent",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the message has been sent",
                        verbose_name="Is Sent",
                    ),
                ),
                (
                    "total_recipients",
                    models.IntegerField(
                        default=0,
                        help_text="Total number of recipients",
                        verbose_name="Total Recipients",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this message",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageGroupFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_filters",
                        to="courses.group",
                        verbose_name="Group",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_filters",
                        to="mailing.message",
                        verbose_name="Message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Group Filter",
                "verbose_name_plural": "Message Group Filters",
                "unique_together": {("message", "group")},
            },
        ),
        migrations.CreateModel(
            name="MessageRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Is Read")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Read At"),
                ),
                (
                    "received_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Received At"),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="mailing.message",
                        verbose_name="Message",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recipient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Recipient",
                "verbose_name_plural": "Message Recipients",
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="mailing_mes_recipie_2dc3b6_idx",
                    ),
                    models.Index(
                        fields=["message", "recipient"],
                        name="mailing_mes_message_b6ad5b_idx",
                    ),
                ],
                "unique_together": {("message", "recipient")},
            },
        ),
    ]
